### ISSUE TITLE
Вопрос по установке сервиса

### ISSUE THREAD

**Issue by AspirineT** [bigov/phonebook#1]
Доброго дня. Планирую поднять этот сервис на базе Redos (CentOS). После установки mysql на сервере, можно подробнее описать дальнейшие действия по установке? Заранее большое спасибо.

**Comment by bigov** [comment]
Здравствуйте. Сервис будет работать на любой ОС, но с ограничением по версии PHP. На свежей версии "не взлетит", надо переделывать. Если кому-то интересно - велкам.

Более подробную инструкцию по запуску в ближайшие день-два сделаю.

**Comment by AspirineT** [comment]
Да, спасибо. Инструкция очень нужна. Я установил php 7.4.11. Получается на ней не будет работать? Тогда какую установить? Сейчас при входе на сервис через браузер такая ошибка: 
![image](https://user-images.githubusercontent.com/93203389/151151735-bc8c237e-7b3f-48b2-940d-3948c89b4d6d.png)
хотя разрешения даны полностью на каталог /var/www/html/phonebook/

**Comment by AspirineT** [comment]
Доброго дня! Подскажите, ожидать инструкцию или нет?

**Comment by bigov** [comment]
https://github.com/bigov/phonebook/wiki#%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

**Comment by bigov** [comment]
> Доброго дня! Подскажите, ожидать инструкцию или нет?

Доброго дня. Я переписал весь старый код, теперь не требуется mysql, и все работает на текущей версии PHP. Но для работы нужно php-sqlite3. Если у Вас появятся какие-то сложности с установкой, то пожалуйста сообщите - я помогу разобраться.

**Comment by AspirineT** [comment]
Спасибо! На следующей неделе попробую и обязательно сообщу.

**Comment by AspirineT** [comment]
Добрый день! Удалось сегодня попробовать. Но, увы что-то не получается. 
![изображение](https://user-images.githubusercontent.com/93203389/154790912-60a0f5fc-183f-44f7-97c6-e507cb24c0c9.png)
Apache модуль mod_rewrite.so - есть
PHP модули: php_mbstring, php_sqlite3 - установлены
![изображение](https://user-images.githubusercontent.com/93203389/154791088-8cd56b75-2346-4f40-9b9c-d78fc493c01c.png)
Разрешения выставил на все папки и для потомков в т.ч.
![изображение](https://user-images.githubusercontent.com/93203389/154791161-e51293c6-c9de-4049-bd13-72963ccbb59e.png)
Как итог: 
![изображение](https://user-images.githubusercontent.com/93203389/154791233-34b9a06c-1d9d-4d49-8c6c-c8d7baa83a50.png)
![изображение](https://user-images.githubusercontent.com/93203389/154791274-bc7d2e45-8667-47cb-9d1f-26481843f7ee.png)
Сам апач работает (любая html страница открывается без проблем, если подкинуть),  подозрение, что что-то с php не так.
![изображение](https://user-images.githubusercontent.com/93203389/154791401-2e7e9f8d-0d7b-4ea2-900e-5684712b8e16.png)

**Comment by bigov** [comment]
Рекомендую изучить инструкцию по настройке [Apache + PHP](https://www.php.net/manual/ru/install.php)

**Comment by AspirineT** [comment]
Да, разобрался. Не хватало одного пакета, PHP заработал. Теперь такая ошибка: 
![image](https://user-images.githubusercontent.com/93203389/154915774-9afc1a95-3cb4-473d-ac87-00bba9dff008.png)

**Comment by bigov** [comment]
Если пишет, что нет файла - значит его нет. Очевидно, что вы не установили подмодуль "smarty" при клонировании. Можно исправить это командами:
```bash
cd phonebook
git submodule init
git submodule update
```

Или (если вы скачали архив релиза) установить его непосредственно
```bash
cd phonebook
git submodule add https://github.com/smarty-php/smarty.git inc/smarty
```

**Comment by AspirineT** [comment]
Спасибо. Да, я скачивал zip архив, по старинке. Сейчас заработало. Буду пробовать. 
![image](https://user-images.githubusercontent.com/93203389/154949511-439bfc9f-fe0b-4105-ba92-d0d6ca666eb9.png)

**Comment by AspirineT** [comment]
Здесь есть возможность разграничивать права? Например, кто-то может редактировать, а кто-то только просматривать?
Еще, при добавлении разделов проблем нет, но при удалении или редактировании такая ошибка: 
![image](https://user-images.githubusercontent.com/93203389/154963038-0aa3249c-01cb-410f-a036-e0fc8e1f6caa.png)

**Comment by bigov** [comment]
ошибка исправлена.

**Comment by AspirineT** [comment]
Спасибо, работает! По поводу ограничения возможностей (редактирования) что-то поясните? Может можно скрывать раздел редактирования, как вариант?

**Comment by bigov** [comment]
В коде присутствует функционал ограничения на внесение изменений. Логика работы такая: для внесения изменений необходимо на свой е-майл получить ссылку активации. После активации можно вносить правки, но они не видны сразу, а остаются в "кэше" до момента одобрения. Если правка одобрена, то автор получает плюс к рейтингу доверия. Нет - минус к рейтингу. С рейтингом больше определенного значения изменения становятся видны сразу всем и автор получает возможность одобрять правки других участников с более низким рейтингом. Администратор может управлять рейтингом других участников по своему усмотрению.

Но данный функционал в настоящее время отключен как невостребованный и в целях упрощения использования.

Если будут запросы от заинтересованных пользователей проекта, можно будет активировать какие-то части системы ограничений.

**Comment by AspirineT** [comment]
Планируется использовать данный справочник в локальной сети, доступ к нему нужен для всех пользователей. Поэтому вопрос ограничений конечно актуальный. На счет функционала с ссылками, мне кажется не очень удобно для обычных пользователелей, тем более, что редактировать справочник будут 3, 4 человека в организации.  Возможно ли просто отключать раздел редактирования в коде? Или иметь возможность редактирования с определенных IP, а для всех остальных только функционал просмотра? Можете предложить простой вариант для меня (понятно, что можно просто убрать права на запись в файл phones.sqlite), не прошу Вас утруждаться и активировать функционал ограничений.

**Comment by bigov** [comment]
Оформите пожалуйста это не как продолжние преписки по текущей проблеме, а как новый - запрос фичи. Думаю, можно будет решить. 22.02.2022, 19:40, "AspirineT" ***@***.***>: Планируется использовать данный справочник в локальной сети, доступ к нему нужен для всех пользователей. Поэтому вопрос ограничений конечно актуальный. На счет функционала с ссылками, мне кажется не очень удобно для обычных пользователелей, тем более, что редактировать справочник будут 3, 4 человека в организации. Возможно ли просто отключать раздел редактирования в коде? Или иметь возможность редактирования с определенных IP, а для всех остальных только функционал просмотра? Можете предложить простой вариант для меня (понятно, что можно просто убрать права на запись в файл phones.sqlite), не прошу Вас утруждаться и активировать функционал ограничений.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.You are receiving this because you modified the open/close state.Message ID: ***@***.***>  -- С уважением, Игорь Балезин.
