### ISSUE TITLE
Вопрос по обновлению справочника.

### ISSUE THREAD

**Issue by AspirineT** [bigov/phonebook#5]
Добрый день! Я заметил, что Вы обновили код справочника. Нужно ли обновляться, или там несущественные изменения? И как правильно обновить только измененные файлы прямо с github, есть такая возможность?

**Comment by bigov** [comment]
Для обновления используетcя команда "git pull"

**Comment by AspirineT** [comment]
А, какие изменения были сделаны?

**Comment by bigov** [comment]
> А, какие изменения были сделаны?

Для это тоже [есть команда](https://duckduckgo.com/?q=git%20%D0%BA%D0%B0%D0%BA%20%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C%20%D1%87%D1%82%D0%BE%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B8%D0%BB%D0%BE%D1%81%D1%8C&atb=v297-1)
