### ISSUE TITLE
Ошибка при добавлении сотрудника на вакантную должность.

### ISSUE THREAD

**Issue by AspirineT** [bigov/phonebook#6]
Добрый день! Есть проблема с установкой модуля sqlite3-pcre.  У меня RedOS, пакеты подходят для CentOS и RedHat, но sqlite3-pcre для этих дистрибутивов нет. Можете помочь? Я так понимаю, что из-за этого возникает такая ошибка: 
![image](https://user-images.githubusercontent.com/93203389/185600301-edd28bd4-7dbb-4f81-a18c-8a41e4abf3f4.png)
и вот такая при добавлении сотрудника на вакантную должность:
![image](https://user-images.githubusercontent.com/93203389/185600453-816310d4-3a0b-4f9f-9cc3-c27d131558dd.png)
И в списке вакансий пусто:
![image](https://user-images.githubusercontent.com/93203389/185600560-0b31cf81-fff0-4702-97be-251804c66646.png)

**Comment by bigov** [comment]
https://github.com/ralight/sqlite3-pcre

Думаю, Вам надо искать решение тут.

**Comment by AspirineT** [comment]
Получилось. Ошибка связанная с pcre.so ушла. Остались теперь эти ошибки, при добавлении нового сотрудника:
![image](https://user-images.githubusercontent.com/93203389/186102005-6d334e34-b428-484d-89b8-2a9426ce9ff9.png)
![image](https://user-images.githubusercontent.com/93203389/186102094-d922a74b-160c-4dfd-86d3-7824c3d4a00d.png)

И в списке имеющихся вакансий пусто. 
![image](https://user-images.githubusercontent.com/93203389/186102831-dc475d48-6151-4273-a512-3b20c60f3bbb.png)

**Comment by bigov** [comment]
Опишите пожалуйста, как вы решили проблему с библиотекой, Ваша информация может оказаться полезной для других пользователей RedOS. Папку кэша попробуйте очистить вручную - просто удалите все файлы в директории /var/www/html/phonebook/templates_c

**Comment by AspirineT** [comment]
Добрый день! На РЕДОС 7.3, для установки расширения sqlite3-pcre, я сделал так:
1. Скачал архив по ссылке https://github.com/ralight/sqlite3-pcre/archive/refs/heads/master.zip , распаковал, изменил в Makefile строку в части /lib/sqlite3/pcre.so на /lib64/sqlite3/pcre.so.
2. Установил пакеты dnf install sqlite-devel и dnf install pcre-devel.
3. Перешел в папку с распакованным архивом sqlite3-pcre-master и запустил make install.
4. В файле php.ini, в разделе [sqlite3], прописал путь до расширения pcre.so (sqlite3.extension_dir = "/usr/lib64/sqlite3")
