### ISSUE TITLE
Проблема с отображением справочника при указании корневого каталога.

### ISSUE THREAD

**Issue by AspirineT** [bigov/phonebook#7]
Добрый день! Помогите разобраться. При добавлении директивы DocumentRoot /var/www/html/phonebook в файл конфигурации веб сервера, веб страница начинает отображаться некорректно. Почему так?
![image](https://user-images.githubusercontent.com/93203389/186393917-a8543b75-7144-44d0-9eb8-af97299b81a7.png)

**Comment by bigov** [comment]
В коде Справочника явно указано место расположения - в подкаталоге phonebook. Если на сайте нет других ресурсов, рекомендуется использовать директиву Redirect из корневого каталога в папку Справочника, например так:
``Redirect 301 / http://www.domain2.com/phonebook/``

**Comment by AspirineT** [comment]
Понятно, спасибо!
