### ISSUE TITLE
Как скрыть раздел в дереве Справочника и изменить шрифт?

### ISSUE THREAD

**Issue by AspirineT** [bigov/phonebook#8]
Добрый день! Есть возможность самому скрыть для всех пользователей раздел "Галерея фотографий" и "Скачать справочник в виде файла", но при необходимости открыть тот или иной раздел?  И как менять размер шрифта и отступы в разделе "Структура справочника"?

**Comment by bigov** [comment]
такой функционал не предусмотрен.
